"""
Hypernym tasks for specific hyponyms (elephants, hammers, kites, etc.)

These tasks use data generated by the pipeline where:
- noun1 = the hyponym (e.g., "elephants")
- predicted_hypernym = candidate hypernym
- gpt4_ground_truth = "Yes" or "No"

Each hyponym dataset is registered as a separate task named 'hypernym-{hyponym}'.
"""

import os
import csv
from collections import namedtuple

import sys
_parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _parent_dir not in sys.path:
    sys.path.insert(0, _parent_dir)

from task_registry import register_task
import utils


# Data directory
DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), 'data')

# Named tuple matching the expected format
HypernymItem = namedtuple('HypernymItem', ['noun1', 'noun2', 'taxonomic'])


def load_hyponym_data(hyponym_name, split='train'):
    """
    Load data for a specific hyponym from CSV.
    
    Args:
        hyponym_name: Name of the hyponym (e.g., 'elephants', 'hammers')
        split: 'train' or 'test'
    
    Returns:
        List of HypernymItem namedtuples
    """
    # Find the CSV file
    csv_path = os.path.join(DATA_DIR, f"hypernym_{hyponym_name}_google-gemma-2-2b_{split}.csv")
    
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Data file not found: {csv_path}")
    
    items = []
    with open(csv_path, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Map columns to expected format
            item = HypernymItem(
                noun1=row['noun1'],
                noun2=row['predicted_hypernym'],
                taxonomic=row['gpt4_ground_truth'].lower()  # 'Yes' -> 'yes', 'No' -> 'no'
            )
            items.append(item)
    
    return items


def create_load_data_func(hyponym_name):
    """Factory function to create load_data for a specific hyponym."""
    def load_data(seed=0, split_type='random', sample_negative=False, **kwargs):
        """Load train/test data for this hyponym."""
        L_train = load_hyponym_data(hyponym_name, split='train')
        L_test = load_hyponym_data(hyponym_name, split='test')
        return L_train, L_test
    return load_data


def make_prompt(item, style='generator', shots='zero', gen_response=None, neg=False, variation=0, **kwargs):
    """
    Create prompt for generator or discriminator.
    Uses the same prompt format as hypernym2.
    """
    return utils.make_prompt_hypernymy(
        item,
        style=style,
        shots=shots,
        neg=neg,
        gen_response=gen_response,
        variation=variation
    )


def get_completion(item):
    """Extract generator completion text (the hypernym with leading space)."""
    return " " + item.noun2


def get_label(item):
    """Extract binary label ('yes' or 'no')."""
    return item.taxonomic.strip().lower()


# Discover and register all available hyponym datasets
def discover_hyponym_datasets():
    """Find all hyponym datasets in the data directory."""
    hyponyms = set()
    suffix = '_google-gemma-2-2b_train.csv'
    prefix = 'hypernym_'
    if os.path.exists(DATA_DIR):
        for filename in os.listdir(DATA_DIR):
            # Must match exact pattern: hypernym_{name}_google-gemma-2-2b_train.csv
            if filename.startswith(prefix) and filename.endswith(suffix):
                # Extract hyponym name
                hyponym_name = filename[len(prefix):-len(suffix)]
                # Skip 'car' (old file format without model name)
                if hyponym_name and hyponym_name != 'car':
                    hyponyms.add(hyponym_name)
    return sorted(hyponyms)


# Register each hyponym as a separate task
_registered_hyponyms = []
for hyponym in discover_hyponym_datasets():
    task_name = f'hypernym-{hyponym}'
    
    # Skip if already registered (e.g., hypernym-cars exists elsewhere)
    try:
        register_task({
            'name': task_name,
            'load_data': create_load_data_func(hyponym),
            'make_prompt': make_prompt,
            'get_completion': get_completion,
            'get_label': get_label,
            'batch_size': {'with_ref': 1, 'without_ref': 6},
            'supports_split_types': ['random'],  # These datasets have fixed train/test splits
            'description': f'Hypernym task for {hyponym}',
        })
        _registered_hyponyms.append(task_name)
    except Exception as e:
        print(f"[hypernym_hyponyms] Warning: Could not register {task_name}: {e}")

if _registered_hyponyms:
    print(f"[hypernym_hyponyms] Registered {len(_registered_hyponyms)} tasks: {', '.join(_registered_hyponyms[:5])}{'...' if len(_registered_hyponyms) > 5 else ''}")
