"""
Custom hypernym tasks for specific nouns (cars, fruit, etc.)

These tasks use balanced train/test datasets generated by:
    typicality/generate_hypernym_dataset.py --noun1 <noun>

Each noun gets its own task: hypernym-cars, hypernym-fruit, etc.

Dataset files expected at:
    data/hypernym_{noun}_train.csv
    data/hypernym_{noun}_test.csv

To add a new noun:
    1. Generate data: python typicality/generate_hypernym_dataset.py --noun1 <noun>
    2. Add to REGISTERED_NOUNS list below
    3. The task 'hypernym-<noun>' will be automatically available
"""

import os
import sys
from collections import namedtuple

# Add parent directory to path for imports
_parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _parent_dir not in sys.path:
    sys.path.insert(0, _parent_dir)

from task_registry import register_task

# Import the existing hypernym prompt function from utils
import utils

# Standard Item namedtuple (same as hypernym for compatibility)
Item = namedtuple(
    "Item",
    ["noun1", "noun2", "taxonomic", "sim", "gen_rank", "yesgreater", "argmax"],
)


def create_hypernym_task(noun):
    """
    Factory function to create a hypernym task for a specific noun.
    
    Args:
        noun: The noun name (e.g., 'cars', 'fruit')
    
    Returns:
        Dictionary of task functions for registration
    """
    
    def load_data(seed=0, split_type='random', sample_negative=False, **kwargs):
        """
        Load pre-split balanced train/test data for this noun.
        
        Data is generated by: typicality/generate_hypernym_dataset.py --noun1 <noun>
        """
        import pandas as pd
        from pathlib import Path
        
        train_file = Path(f"../data/hypernym_{noun}_train.csv")
        test_file = Path(f"../data/hypernym_{noun}_test.csv")
        
        if not train_file.exists():
            raise FileNotFoundError(
                f"Training data not found: {train_file}\n"
                f"Generate it with: python typicality/generate_hypernym_dataset.py --noun1 {noun}"
            )
        if not test_file.exists():
            raise FileNotFoundError(
                f"Test data not found: {test_file}\n"
                f"Generate it with: python typicality/generate_hypernym_dataset.py --noun1 {noun}"
            )
        
        train_df = pd.read_csv(train_file)
        test_df = pd.read_csv(test_file)
        
        def df_to_items(df):
            items = []
            for _, row in df.iterrows():
                # Map gpt4_ground_truth to lowercase for taxonomic field
                taxonomic = "yes" if row['gpt4_ground_truth'] == 'Yes' else "no"
                item = Item(
                    noun1=row['noun1'],
                    noun2=row['predicted_hypernym'],
                    taxonomic=taxonomic,
                    sim="high",  # placeholder
                    gen_rank=0,  # placeholder
                    yesgreater="yes",  # placeholder
                    argmax="yes"  # placeholder
                )
                items.append(item)
            return items
        
        L_train = df_to_items(train_df)
        L_test = df_to_items(test_df)
        
        return L_train, L_test
    
    def make_prompt(item, style='generator', shots='zero', gen_response=None, neg=False, variation=0, **kwargs):
        """
        Create prompt using the same format as the base hypernym task.
        """
        return utils.make_prompt_hypernymy(
            item,
            style=style,
            shots=shots,
            neg=neg,
            gen_response=gen_response,
            variation=variation
        )
    
    def get_completion(item):
        """Extract generator completion (the hypernym) with leading space."""
        return " " + item.noun2
    
    def get_label(item):
        """Extract binary label (yes/no)."""
        return item.taxonomic.strip().lower()
    
    return {
        'name': f'hypernym-{noun}',
        'load_data': load_data,
        'make_prompt': make_prompt,
        'get_completion': get_completion,
        'get_label': get_label,
        'batch_size': {'with_ref': 1, 'without_ref': 2},
        'supports_split_types': ['random'],  # Only random - data is pre-split
    }


# ============================================================================
# REGISTERED NOUNS
# ============================================================================
# Add noun names here after generating their datasets.
# Each noun will create a task: hypernym-<noun>
#
# To generate data for a new noun:
#     python typicality/generate_hypernym_dataset.py --noun1 <noun> --total 4000

REGISTERED_NOUNS = [
    # 'cars',  # Now handled by hypernym_hyponyms.py with new file format
    # Add more nouns here as you generate them:
    # 'fruit',
    # 'dogs',
    # 'computers',
]


# Register all noun tasks
for noun in REGISTERED_NOUNS:
    try:
        task_config = create_hypernym_task(noun)
        register_task(task_config)
    except Exception as e:
        # Don't fail if data files don't exist yet - just skip registration
        print(f"[hypernym_custom] Skipping hypernym-{noun}: {e}")

