"""
k-SAT Task - Validates variable assignments against CNF formulas.

Generator task: Given a k-SAT formula, produce a satisfying assignment.
Validator task: Does a given assignment satisfy the formula? (Yes/No)

This task loads data from CSV files generated by scripts/generate_ksat_data.py
"""

import os
import sys
import csv
import random
from collections import namedtuple

# Add parent directory to path for imports
_parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _parent_dir not in sys.path:
    sys.path.insert(0, _parent_dir)

from task_registry import register_task

# Data structure for k-SAT examples
KSATItem = namedtuple('KSATItem', ['formula', 'assignment', 'label', 'satisfying_assignment'])

# Prompt-completion pair (required by eval.py)
PromptCompletion = namedtuple('PromptCompletion', ['prompt', 'completion'])


# ============================================================================
# Few-shot examples for prompts
# ============================================================================

# Few-shot examples for 2-SAT with 4 variables (x0-x3)
FEW_SHOT_EXAMPLES_2SAT_4VARS = [
    # Positive example 1: (x0 ∨ x1) ∧ (¬x1 ∨ x2) - satisfied by x0=1, x1=0
    {
        'formula': '(x0 ∨ x1) ∧ (¬x1 ∨ x2)',
        'assignment': 'x0=1, x1=0, x2=0, x3=0',
        'label': 'yes'
    },
    # Negative example 1: (x0 ∨ x1) ∧ (¬x0 ∨ ¬x1) - NOT satisfied by x0=0, x1=0
    {
        'formula': '(x0 ∨ x1) ∧ (¬x0 ∨ ¬x1)',
        'assignment': 'x0=0, x1=0, x2=0, x3=0',
        'label': 'no'
    },
    # Positive example 2: (¬x0 ∨ x2) ∧ (x1 ∨ ¬x2) - satisfied by x0=0, x1=1, x2=1
    {
        'formula': '(¬x0 ∨ x2) ∧ (x1 ∨ ¬x2)',
        'assignment': 'x0=0, x1=1, x2=1, x3=0',
        'label': 'yes'
    },
    # Negative example 2: (x0 ∨ x3) ∧ (¬x0 ∨ ¬x3) - NOT satisfied by x0=0, x3=0
    {
        'formula': '(x0 ∨ x3) ∧ (¬x0 ∨ ¬x3)',
        'assignment': 'x0=0, x1=0, x2=0, x3=0',
        'label': 'no'
    },
]

# Few-shot examples for 2-SAT with 10 variables (x0-x9)
FEW_SHOT_EXAMPLES_2SAT_10VARS = [
    # Positive example 1: (x0 ∨ x1) ∧ (¬x1 ∨ x2) - satisfied by x0=1, x1=0
    {
        'formula': '(x0 ∨ x1) ∧ (¬x1 ∨ x2)',
        'assignment': 'x0=1, x1=0, x2=0, x3=0, x4=0, x5=0, x6=0, x7=0, x8=0, x9=0',
        'label': 'yes'
    },
    # Negative example 1: (x0 ∨ x1) ∧ (¬x0 ∨ ¬x1) - NOT satisfied by x0=0, x1=0
    {
        'formula': '(x0 ∨ x1) ∧ (¬x0 ∨ ¬x1)',
        'assignment': 'x0=0, x1=0, x2=0, x3=0, x4=0, x5=0, x6=0, x7=0, x8=0, x9=0',
        'label': 'no'
    },
    # Positive example 2: (¬x0 ∨ x2) ∧ (x1 ∨ ¬x2) - satisfied by x0=0, x1=1, x2=1
    {
        'formula': '(¬x0 ∨ x2) ∧ (x1 ∨ ¬x2)',
        'assignment': 'x0=0, x1=1, x2=1, x3=0, x4=0, x5=0, x6=0, x7=0, x8=0, x9=0',
        'label': 'yes'
    },
    # Negative example 2: (x0 ∨ x3) ∧ (¬x0 ∨ ¬x3) - NOT satisfied by x0=0, x3=0
    {
        'formula': '(x0 ∨ x3) ∧ (¬x0 ∨ ¬x3)',
        'assignment': 'x0=0, x1=0, x2=0, x3=0, x4=0, x5=0, x6=0, x7=0, x8=0, x9=0',
        'label': 'no'
    },
]

# For 3-SAT with 4 variables
FEW_SHOT_EXAMPLES_3SAT_4VARS = [
    {
        'formula': '(x0 ∨ x1 ∨ x2) ∧ (¬x0 ∨ x1 ∨ ¬x2)',
        'assignment': 'x0=1, x1=1, x2=0, x3=0',
        'label': 'yes'
    },
    {
        'formula': '(x0 ∨ x1 ∨ x2) ∧ (¬x0 ∨ ¬x1 ∨ ¬x2)',
        'assignment': 'x0=0, x1=0, x2=0, x3=0',
        'label': 'no'
    },
    {
        'formula': '(¬x0 ∨ x1 ∨ x2) ∧ (x0 ∨ ¬x1 ∨ x2)',
        'assignment': 'x0=0, x1=0, x2=1, x3=0',
        'label': 'yes'
    },
    {
        'formula': '(x0 ∨ x1 ∨ x2) ∧ (¬x0 ∨ x1 ∨ x2)',
        'assignment': 'x0=0, x1=0, x2=0, x3=0',
        'label': 'no'
    },
]

# For 3-SAT with 10 variables
FEW_SHOT_EXAMPLES_3SAT_10VARS = [
    {
        'formula': '(x0 ∨ x1 ∨ x2) ∧ (¬x0 ∨ x1 ∨ ¬x2)',
        'assignment': 'x0=1, x1=1, x2=0, x3=0, x4=0, x5=0, x6=0, x7=0, x8=0, x9=0',
        'label': 'yes'
    },
    {
        'formula': '(x0 ∨ x1 ∨ x2) ∧ (¬x0 ∨ ¬x1 ∨ ¬x2)',
        'assignment': 'x0=0, x1=0, x2=0, x3=0, x4=0, x5=0, x6=0, x7=0, x8=0, x9=0',
        'label': 'no'
    },
    {
        'formula': '(¬x0 ∨ x1 ∨ x2) ∧ (x0 ∨ ¬x1 ∨ x2)',
        'assignment': 'x0=0, x1=0, x2=1, x3=0, x4=0, x5=0, x6=0, x7=0, x8=0, x9=0',
        'label': 'yes'
    },
    {
        'formula': '(x0 ∨ x1 ∨ x2) ∧ (¬x0 ∨ x1 ∨ x2) ∧ (x0 ∨ ¬x1 ∨ x2) ∧ (x0 ∨ x1 ∨ ¬x2)',
        'assignment': 'x0=0, x1=0, x2=0, x3=0, x4=0, x5=0, x6=0, x7=0, x8=0, x9=0',
        'label': 'no'
    },
]


def get_few_shot_examples(k=2, n_vars=4):
    """Get few-shot examples for k-SAT with n_vars variables."""
    if k == 2:
        if n_vars == 10:
            return FEW_SHOT_EXAMPLES_2SAT_10VARS
        else:  # Default to 4 vars
            return FEW_SHOT_EXAMPLES_2SAT_4VARS
    elif k == 3:
        if n_vars == 10:
            return FEW_SHOT_EXAMPLES_3SAT_10VARS
        else:  # Default to 4 vars
            return FEW_SHOT_EXAMPLES_3SAT_4VARS
    else:
        # Default to 2-SAT 4 vars
        return FEW_SHOT_EXAMPLES_2SAT_4VARS


# ============================================================================
# Data loading
# ============================================================================

def load_csv_data(filepath):
    """Load k-SAT data from a CSV file."""
    items = []
    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            item = KSATItem(
                formula=row['formula'],
                assignment=row['assignment'],
                label=row['label'].strip().lower(),
                satisfying_assignment=row.get('satisfying_assignment', '')
            )
            items.append(item)
    return items


def load_data(seed=0, split_type='random', sample_negative=False, k=2, **kwargs):
    """
    Load and return train/test splits for k-SAT task.
    
    Args:
        seed: Random seed for shuffling
        split_type: Only 'random' is supported for this task
        sample_negative: Not used for this task (data already balanced)
        k: k value for k-SAT (2 for 2-SAT, 3 for 3-SAT)
    
    Returns:
        L_train, L_test: Lists of KSATItem namedtuples
    """
    # Find data directory
    data_dir = os.path.join(_parent_dir, '..', 'data')
    
    train_file = os.path.join(data_dir, f'{k}sat_train.csv')
    test_file = os.path.join(data_dir, f'{k}sat_test.csv')
    
    if not os.path.exists(train_file):
        raise FileNotFoundError(
            f"Training data not found: {train_file}\n"
            f"Run: python scripts/generate_ksat_data.py --k {k}"
        )
    if not os.path.exists(test_file):
        raise FileNotFoundError(
            f"Test data not found: {test_file}\n"
            f"Run: python scripts/generate_ksat_data.py --k {k}"
        )
    
    L_train = load_csv_data(train_file)
    L_test = load_csv_data(test_file)
    
    # Shuffle with seed
    random.seed(seed)
    random.shuffle(L_train)
    random.shuffle(L_test)
    
    print(f"Loaded {k}-SAT data: {len(L_train)} train, {len(L_test)} test")
    
    return L_train, L_test


# ============================================================================
# Prompt generation
# ============================================================================

def make_generator_prompt_zero_shot(item):
    """
    Zero-shot generator prompt: Given formula, produce satisfying assignment.
    """
    prompt = (
        f"Given the following Boolean formula in CNF (conjunctive normal form):\n"
        f"{item.formula}\n\n"
        f"Provide a variable assignment that satisfies this formula.\n"
        f"Assignment:"
    )
    return prompt


def detect_n_vars(assignment_str):
    """Detect number of variables from assignment string like 'x0=1, x1=0, x2=0, x3=0'."""
    # Count comma-separated parts
    return len(assignment_str.split(', '))


def make_generator_prompt_few_shot(item, k=2, n_vars=None):
    """
    Few-shot generator prompt with examples.
    """
    # Auto-detect n_vars from item if not provided
    if n_vars is None:
        n_vars = detect_n_vars(item.assignment)
    
    examples = get_few_shot_examples(k, n_vars)
    
    # Filter to only positive examples for generator
    positive_examples = [ex for ex in examples if ex['label'] == 'yes']
    
    prompt = "Given a Boolean formula in CNF, provide a variable assignment that satisfies it.\n\n"
    
    for i, ex in enumerate(positive_examples[:2]):
        prompt += f"Formula: {ex['formula']}\n"
        prompt += f"Assignment: {ex['assignment']}\n\n"
    
    prompt += f"Formula: {item.formula}\n"
    prompt += "Assignment:"
    
    return prompt


def make_discriminator_prompt_zero_shot(item, gen_response=None):
    """
    Zero-shot discriminator prompt: Does assignment satisfy formula?
    
    Args:
        item: KSATItem with formula
        gen_response: The assignment to validate (if None, uses item.assignment)
    """
    assignment = gen_response if gen_response else item.assignment
    
    prompt = (
        f"Given the Boolean formula in CNF:\n"
        f"{item.formula}\n\n"
        f"Does the variable assignment \"{assignment}\" satisfy this formula?\n"
        f"Answer with Yes or No.\n"
        f"Answer:"
    )
    return prompt


def make_discriminator_prompt_few_shot(item, gen_response=None, k=2, n_vars=None):
    """
    Few-shot discriminator prompt with examples.
    """
    assignment = gen_response if gen_response else item.assignment
    
    # Auto-detect n_vars from item if not provided
    if n_vars is None:
        n_vars = detect_n_vars(item.assignment)
    
    examples = get_few_shot_examples(k, n_vars)
    
    prompt = (
        "Determine if a variable assignment satisfies a Boolean formula in CNF.\n"
        "Answer with Yes or No.\n\n"
    )
    
    for ex in examples[:4]:
        answer = "Yes" if ex['label'] == 'yes' else "No"
        prompt += f"Formula: {ex['formula']}\n"
        prompt += f"Assignment: {ex['assignment']}\n"
        prompt += f"Answer: {answer}\n\n"
    
    prompt += f"Formula: {item.formula}\n"
    prompt += f"Assignment: {assignment}\n"
    prompt += "Answer:"
    
    return prompt


def get_completion(item):
    """
    Get the generator completion (the satisfying assignment).
    
    For the generator task, this is the correct answer to produce.
    We use the satisfying_assignment if available, otherwise the assignment.
    """
    if item.satisfying_assignment:
        return " " + item.satisfying_assignment
    return " " + item.assignment


def get_label(item):
    """
    Get the ground truth label ('yes' or 'no').
    
    Indicates whether the assignment satisfies the formula.
    """
    return item.label.strip().lower()


def make_prompt(item, style='generator', shots='zero', gen_response=None, neg=False, variation=0, k=2, n_vars=None, **kwargs):
    """
    Create prompt for generator or discriminator.
    
    Args:
        item: KSATItem namedtuple
        style: 'generator' or 'discriminator'
        shots: 'zero' or 'few'
        gen_response: For discriminator, the assignment to validate
        neg: Not used for this task
        variation: Prompt variation (for future use)
        k: k value for k-SAT (affects few-shot examples)
        n_vars: Number of variables (auto-detected from item if None)
    
    Returns:
        PromptCompletion namedtuple with .prompt and .completion
    """
    if style == 'generator':
        if shots == 'zero':
            prompt = make_generator_prompt_zero_shot(item)
        else:
            prompt = make_generator_prompt_few_shot(item, k=k, n_vars=n_vars)
        # Generator completion is the satisfying assignment
        completion = get_completion(item)
        return PromptCompletion(prompt=prompt, completion=completion)
    else:  # discriminator
        if shots == 'zero':
            prompt = make_discriminator_prompt_zero_shot(item, gen_response)
        else:
            prompt = make_discriminator_prompt_few_shot(item, gen_response, k=k, n_vars=n_vars)
        # Discriminator completion is Yes or No
        label = get_label(item)
        completion = " Yes" if label == 'yes' else " No"
        return PromptCompletion(prompt=prompt, completion=completion)


# ============================================================================
# Task Registration
# ============================================================================

# Register 2-SAT task
register_task({
    'name': '2sat',
    'load_data': lambda **kwargs: load_data(k=2, **kwargs),
    'make_prompt': lambda item, **kwargs: make_prompt(item, k=2, **kwargs),
    'get_completion': get_completion,
    'get_label': get_label,
    'batch_size': {'with_ref': 1, 'without_ref': 4},
    'supports_split_types': ['random'],
    'description': '2-SAT satisfiability checking task',
})

# Register 3-SAT task
register_task({
    'name': '3sat',
    'load_data': lambda **kwargs: load_data(k=3, **kwargs),
    'make_prompt': lambda item, **kwargs: make_prompt(item, k=3, **kwargs),
    'get_completion': get_completion,
    'get_label': get_label,
    'batch_size': {'with_ref': 1, 'without_ref': 4},
    'supports_split_types': ['random'],
    'description': '3-SAT satisfiability checking task',
})

