#!/usr/bin/env python3
"""Harvest the HumanEval held-out val-loss CSVs and build the §2.3 table + figures.

Mirrors the original report's "Held-out Validation Loss" section: the 3 loss components
(preference, NLL-G, NLL-V) recomputed on the held-out TEST set for base + epoch{0,1,2},
for each (model, dataset, setting). Reads the per-job CSVs written by compute_val_loss_he.py.

Recovery is a single command (no in-session state needed):
    python scripts/build_he_valloss_section.py            # run on mll, matplotlib venv
Outputs:
    analysis/tables/he_val_loss.tex     LaTeX table (all present cells)
    analysis/plots/he_val_loss_<model>.png  one 2x3 figure per model (rows=dataset, cols=loss)
Partial runs are fine: missing cells are reported and simply omitted.

Run on mll in a venv with pandas + matplotlib, e.g. /datastor2/jdr/venvs/qwen35.
"""
import sys
from pathlib import Path

import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
CSV_DIR = REPO / "outputs-he-valloss"
TAB = REPO / "analysis" / "tables" / "he_val_loss.tex"
PLOTDIR = REPO / "analysis" / "plots"

MODELS = {"gemma4": "gemma-4-31b", "qwen": "qwen-3.5-9b"}
DATASETS = {"cu": "upper", "cm": "multi"}
# setting code -> (display label, plot order)
SETTINGS = {
    "s1": "SFT",
    "s2": "RankAlign",
    "s3": "New+fsx",
    "s4": "FLORA-PMI (selfTC)",
    "s7": "FLORA-Neg (negTC)",
}
CKPT_ORDER = ["base", "epoch0", "epoch1", "epoch2"]
CKPT_X = {"base": -1, "epoch0": 0, "epoch1": 1, "epoch2": 2}  # base plotted left of ep0
LOSSES = [
    ("preference_loss", "Preference loss"),
    ("nll_generator_loss", "NLL-G (generator)"),
    ("nll_validator_loss", "NLL-V (validator)"),
]


def load_all():
    """Return dict[(model_code, ds_code, setting)] -> dataframe(checkpoint-indexed)."""
    out = {}
    if not CSV_DIR.exists():
        print(f"No CSV dir {CSV_DIR}")
        return out
    for f in sorted(CSV_DIR.glob("he_val_loss_*.csv")):
        if "_canary" in f.name:
            continue
        # he_val_loss_<model>_<ds>_s<S>.csv
        stem = f.stem[len("he_val_loss_"):]
        parts = stem.split("_")
        if len(parts) != 3:
            print(f"  [skip] unexpected name: {f.name}")
            continue
        model_code, ds_code, setting = parts
        try:
            df = pd.read_csv(f)
        except Exception as e:  # noqa: BLE001 — report, don't hide
            print(f"  [skip] unreadable {f.name}: {e}")
            continue
        out[(model_code, ds_code, setting)] = df
    return out


def build_table(data):
    rows = []
    for (mc, dc, s), df in sorted(data.items()):
        for _, r in df.iterrows():
            rows.append({
                "model": MODELS.get(mc, mc), "dataset": DATASETS.get(dc, dc),
                "setting": SETTINGS.get(s, s), "checkpoint": r["checkpoint"],
                "pref": r["preference_loss"], "nllg": r["nll_generator_loss"],
                "nllv": r["nll_validator_loss"], "total": r["total_loss"],
            })
    if not rows:
        print("No data for table.")
        return
    df = pd.DataFrame(rows)
    lines = [
        "% Auto-generated by scripts/build_he_valloss_section.py — do not edit by hand.",
        "\\begin{tabular}{lll l rrrr}", "\\toprule",
        "Model & Data & Setting & Ckpt & Pref & NLL-G & NLL-V & Total \\\\", "\\midrule",
    ]
    prev = None
    for _, r in df.iterrows():
        key = (r["model"], r["dataset"], r["setting"])
        m = r["model"] if key != prev else ""
        d = r["dataset"] if key != prev else ""
        st = r["setting"] if key != prev else ""
        if key != prev and prev is not None:
            lines.append("\\midrule")
        prev = key
        lines.append(f"{m} & {d} & {st} & {r['checkpoint']} & "
                     f"{r['pref']:.3f} & {r['nllg']:.2f} & {r['nllv']:.3f} & {r['total']:.2f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    TAB.parent.mkdir(parents=True, exist_ok=True)
    TAB.write_text("\n".join(lines) + "\n")
    print(f"wrote {TAB}  ({len(df)} rows)")


def build_figures(data):
    for mc, mname in MODELS.items():
        present = {(dc, s): df for (m, dc, s), df in data.items() if m == mc}
        if not present:
            print(f"  [fig] no data for {mname}; skip")
            continue
        fig, axes = plt.subplots(2, 3, figsize=(15, 8), squeeze=False)
        for ri, (dc, dname) in enumerate(DATASETS.items()):
            for ci, (col, clabel) in enumerate(LOSSES):
                ax = axes[ri][ci]
                base_val = None
                for s, slabel in SETTINGS.items():
                    df = present.get((dc, s))
                    if df is None:
                        continue
                    d = df.set_index("checkpoint")
                    xs, ys = [], []
                    for ck in CKPT_ORDER:
                        if ck in d.index:
                            xs.append(CKPT_X[ck]); ys.append(float(d.loc[ck, col]))
                            if ck == "base":
                                base_val = float(d.loc[ck, col])
                    # plot trained epochs as a line; base handled as dashed ref below
                    ep_xy = [(x, y) for x, y in zip(xs, ys) if x >= 0]
                    if ep_xy:
                        ax.plot([x for x, _ in ep_xy], [y for _, y in ep_xy],
                                marker="o", label=slabel)
                if base_val is not None:
                    ax.axhline(base_val, ls="--", color="black", lw=1, label="base" if (ri == 0 and ci == 0) else None)
                ax.set_title(f"{dname} — {clabel}")
                ax.set_xticks([0, 1, 2]); ax.set_xticklabels(["ep0", "ep1", "ep2"])
                if ci == 0:
                    ax.set_ylabel(f"{dname}\n{clabel}")
        handles, labels = axes[0][0].get_legend_handles_labels()
        fig.legend(handles, labels, loc="upper center", ncol=6, fontsize=9)
        fig.suptitle(f"Held-out test loss across checkpoints — {mname}", y=0.995)
        fig.tight_layout(rect=[0, 0, 1, 0.95])
        out = PLOTDIR / f"he_val_loss_{mname}.png"
        PLOTDIR.mkdir(parents=True, exist_ok=True)
        fig.savefig(out, dpi=130, bbox_inches="tight")
        plt.close(fig)
        print(f"wrote {out}")


def report_coverage(data):
    print("\n=== coverage (20 expected cells) ===")
    have = set(data.keys())
    missing = []
    for mc in MODELS:
        for dc in DATASETS:
            for s in SETTINGS:
                tag = f"{mc}/{dc}/{s}"
                if (mc, dc, s) in have:
                    n = len(data[(mc, dc, s)])
                    flag = "OK" if n >= 4 else f"PARTIAL({n}/4)"
                    print(f"  {tag:22s} {flag}")
                else:
                    missing.append(tag)
    print(f"present={len(have)}/20  missing={len(missing)}")
    if missing:
        print("  MISSING:", ", ".join(missing))


def main():
    data = load_all()
    report_coverage(data)
    build_table(data)
    build_figures(data)
    print("\nDone.")


if __name__ == "__main__":
    sys.exit(main())
